### ISSUE TITLE
Render seems to not work

### ISSUE THREAD

**Issue by ntcmp2u** [ise-uiuc/nnsmith#121]
Hi, I'm seeking a way to generate runable python code from bug report directory, so that I can reproduce bugs without NNSmith's code. I found that there is a class named ``Render`` that may help me to do this. However, It does not work well when I want to emit a ``TorchModel``. It seems that ``fx.symbolic_trace`` cannot generate the model declaration in ``TorchMdel.emit_def()``. Is the ``Render`` supposed to work but I did not use it right? Or they are just some deprecated code?

**Comment by ganler** [comment]
Hi I implemented the render in #107 a few months ago. I would not say it is strictly tested but I have not encountered any major issues so far. 

You are welcome to check out the examples in the unit tests: https://github.com/ise-uiuc/nnsmith/blob/main/tests/torch/test_render.py

Or please file a concrete bug so that I can help you diagnose. Thanks.

**Comment by ganler** [comment]
Could you let me know ur PyTorch version? Thanks.

**Comment by ganler** [comment]
Sorry for the late reply. I am looking into the bug right now. While I have fixed your issue partially in #122, the most critical issue here, aka the undefined variable name `_tensor_constant0` is introduced by PyTorch's model-to-code translation when referring to the parameter over a user-provided map.

I will either find other ways to implement the symbolic tracing or report a bug to PyTorch to fix it.

**Comment by ganler** [comment]
OK, got a workaround by referencing parameters as object attributes which makes your example work. Feel free to retry after the PR gets merged.

![image](https://github.com/ise-uiuc/nnsmith/assets/38074777/19393285-c8b2-4063-a2cf-f37de213e579)

**Comment by SoftEngineerTeam** [comment]
I tried to rewrite the render of the torch version to the tensorflow, but encountered some problems. Could you provide a render of the tensorflow version?
