### ISSUE TITLE
🐛 [BUG] - There is a problem with relative import in `fuzz.py`

### ISSUE THREAD

**Issue by shaoyuyoung** [ise-uiuc/nnsmith#124]
### Description

Hi, authors.

When I tried to reproduce the experiment, I had a problem in this step: [Step 2: Run NNSmith over instrumented SUT](https://github.com/ise-uiuc/nnsmith/tree/main/experiments#step-2-run-nnsmith-over-instrumented-sut)

When I wanted to run the fuzz.py below:
```
python nnsmith/cli/fuzz.py  fuzz.time=4h fuzz.root=${PATH_TO_REPORT} \
                            model.type=torch backend.type=pt2        \
                            filter.type="[nan,inf,dup]"              \
                            fuzz.save_test=${PATH_TO_SAVE_TESTS}
```
A relative import error occurred.

To be honest, I'm not quite sure if there's something wrong with the structure of  project directory or my operation.

Here is the error log:
```
Traceback (most recent call last):
  File "nnsmith/cli/fuzz.py", line 13, in <module>
    from nnsmith.abstract.extension import activate_ext
ModuleNotFoundError: No module named 'nnsmith.abstract.extension'
```

Looking forward to your reply.
Thx in advance :)

### Installation

Source file without edits

### Reproduction

```bash
python nnsmith/cli/fuzz.py  fuzz.time=4h fuzz.root=${PATH_TO_REPORT} \
                            model.type=torch backend.type=pt2        \
                            filter.type="[nan,inf,dup]"              \
                            fuzz.save_test=${PATH_TO_SAVE_TESTS}
```
```


### Screenshots

_No response_

### Logs

_No response_

### Front-end framework

_No response_

### Version of the front-end framework

_No response_

### Back-end engine

_No response_

### Version of the front-end engine

_No response_

### Other context

_No response_

**Comment by ganler** [comment]
If you are directly using NNSmith thru `git clone`, have you set `PYTHONPATH=${REPO_ROOT}`?

```shell
git clone git@github.com:ise-uiuc/nnsmith.git
cd nnsmith
export PYTHONPATH=$PWD
# ... some other commands
```

Thanks for bringing up. I had that specified in the [`CONTRIBUTING.md`](https://github.com/ise-uiuc/nnsmith/blob/main/doc/CONTRIBUTING.md#submitting-a-pr) but shall also repeat in the experimental instructions.

**Comment by shaoyuyoung** [comment]
Thx, Jiawei

It would be nice if the experimental instructions could be updated and described in more detail.

Nonetheless, NNSmith is a landmark and solid piece of work!
