### ISSUE TITLE
Problems encountered while compiling the onnx model

### ISSUE THREAD

**Issue by Zeus1116** [ise-uiuc/nnsmith#126]
I created an nnsmith environment using Conda and installed the required libraries according to the installation tutorial "python3- m pip install" nnsmith [torch, onnx, tvm, onnxruntime] "-- upgrade" in cli.md. I can generate the onnx model normally, but I encountered an issue when trying to debug this model locally.
When I used the command "nnsmith.model_exec model.type=onnx backend.type=onnxruntime model.path=nnsmith_output/model.onnx", an AttributeError has occurred
module 'onnx' has no attribute '_serialize'
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/f5391685-116d-4c6f-9638-d87fe08982ba)

This seems to be an issue with the onnx version, so I checked the onnx version and found that the current onnx version is 1.15.0,  then I reinstalled version 1.14.0 of onnx, then I run the same command again, the onnx model will compile and run smoothly.
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/991481db-72bf-467c-acf6-a2cc07a9ae5b)

**Comment by Zeus1116** [comment]
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/1d07b116-6368-46d2-a6e7-ce04e228db48)
I entered the tvm environment to reinstall the required configuration for nnsmith and ran the command "nnsmith. model_exec model. type=onnx"\

Backend. type=onnxruntime\

Model. path=nnsmith_ Output/model.onnx\

Cmp. with='{type: tvm, optmax: true, target: CPU}' 'conducted differential testing, but encountered an error as shown in the above figure. Can someone help me identify the cause.

**Comment by ganler** [comment]
Thanks for reporting the issue. Looks like you are right, `onnx` updated their API in `1.15.0` to `load_from_string`. Please bear a bit by downgrading the onnx versions for now before I brought up a fix.

**Comment by ganler** [comment]
> ![image](https://private-user-images.githubusercontent.com/97088810/292075340-1d07b116-6368-46d2-a6e7-ce04e228db48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjg0OTEsIm5iZiI6MTcwMzEyODE5MSwicGF0aCI6Ii85NzA4ODgxMC8yOTIwNzUzNDAtMWQwN2IxMTYtNjM2OC00NmQyLWE2ZTctY2UwNGUyMjhkYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAzMDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwODIwMTFmZDFiZjZjYjAyZTJjMjJmYzUwYzhhODgwODJjMWZlNzIxYThlYzQ1MDhjYjQ2MmVjMjBmN2NjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KYAaKJaOoFElFuD7-0U7flNxHmxsu5WJMYwAirD7PSU) I entered the tvm environment to reinstall the required configuration for nnsmith and ran the command "nnsmith. model_exec model. type=onnx"\
> 
> Backend. type=onnxruntime\
> 
> Model. path=nnsmith_ Output/model.onnx\
> 
> Cmp. with='{type: tvm, optmax: true, target: CPU}' 'conducted differential testing, but encountered an error as shown in the above figure. Can someone help me identify the cause.

Well, this is a TVM problem and nnsmith cannot help here. 

More specifically, the pre-built TVM binary is compiled using a GLibC version which is newer than what your OS has right now. You can either recompile TVM locally to use your local glibc or install a newer glibc in conda.

**Comment by Zeus1116** [comment]
> > ![image](https://private-user-images.githubusercontent.com/97088810/292075340-1d07b116-6368-46d2-a6e7-ce04e228db48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMjg0OTEsIm5iZiI6MTcwMzEyODE5MSwicGF0aCI6Ii85NzA4ODgxMC8yOTIwNzUzNDAtMWQwN2IxMTYtNjM2OC00NmQyLWE2ZTctY2UwNGUyMjhkYjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDAzMDk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwODIwMTFmZDFiZjZjYjAyZTJjMjJmYzUwYzhhODgwODJjMWZlNzIxYThlYzQ1MDhjYjQ2MmVjMjBmN2NjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KYAaKJaOoFElFuD7-0U7flNxHmxsu5WJMYwAirD7PSU) I entered the tvm environment to reinstall the required configuration for nnsmith and ran the command "nnsmith. model_exec model. type=onnx"\
> > Backend. type=onnxruntime\
> > Model. path=nnsmith_ Output/model.onnx\
> > Cmp. with='{type: tvm, optmax: true, target: CPU}' 'conducted differential testing, but encountered an error as shown in the above figure. Can someone help me identify the cause.
> 
> Well, this is a TVM problem and nnsmith cannot help here.
> 
> More specifically, the pre-built TVM binary is compiled using a GLibC version which is newer than what your OS has right now. You can either recompile TVM locally to use your local glibc or install a newer glibc in conda.

I understand. Thanks for your help.
