### ISSUE TITLE
[Help wanted] How to get the shape of the output tensor of a operator

### ISSUE THREAD

**Issue by Zeus1116** [ise-uiuc/nnsmith#132]
![graph](https://github.com/ise-uiuc/nnsmith/assets/97088810/cfe6dbbb-422b-44eb-8118-895894274ebb)
How is the shape of the output tensor of each operator obtained in the image output by pygraphviz?

**Comment by ganler** [comment]
Thanks for the question. The overall procedure of getting the output image is: GIR - dot file - graphics output (.png). 

You can see the to_dot function in https://github.com/ise-uiuc/nnsmith/blob/main/nnsmith/gir.py

**Comment by Zeus1116** [comment]
> Thanks for the question. The overall procedure of getting the output image is: GIR - dot file - graphics output (.png).
> 
> You can see the to_dot function in https://github.com/ise-uiuc/nnsmith/blob/main/nnsmith/gir.py

thanks!

**Comment by ganler** [comment]
Am closing the issue but feel free to reopen it if you have follow-up questions :D
