### ISSUE TITLE
[Help wanted] How to get the result of executing model_exec.py?

### ISSUE THREAD

**Issue by Zeus1116** [ise-uiuc/nnsmith#133]
How do I know if this model has caused an error after executing the  "nnsmith.model_exec model.type=onnx backend.type=onnxruntime model.path=nnsmith_output/model.onnx", " nnsmith.model_exec  model.type=onnx                        \
                    backend.type=onnxruntime               \
                    model.path=nnsmith_output/model.onnx   \
                    cmp.with='{type:tvm, optmax:true, target:cpu}'"?

**Comment by lazycal** [comment]
I think it will show the error in console like this 
<img width="1186" alt="image" src="https://github.com/ise-uiuc/nnsmith/assets/7333325/87fb0958-cb19-4eaa-abae-1a5c4c868c6d">

Looks like you can also specify `cmp.save=/path/to/folder` (https://github.com/ise-uiuc/nnsmith/blob/4061eb7347cc51880329624127113c229a7f6209/nnsmith/config/main.yaml#L65a) to save the bug report.

**Comment by Zeus1116** [comment]
> I think it will show the error in console like this <img alt="image" width="1186" src="https://private-user-images.githubusercontent.com/7333325/313365297-87fb0958-cb19-4eaa-abae-1a5c4c868c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTcyNTcsIm5iZiI6MTcxMDgxNjk1NywicGF0aCI6Ii83MzMzMzI1LzMxMzM2NTI5Ny04N2ZiMDk1OC1jYjE5LTRlYWEtYWJhZS0xYTVjNGM4NjhjNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDI1NTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI2N2IyNTcwYjYzNjExMzllNDNmNzZhMmQ1MzliNzViZmY5M2ZjY2RhODY5MDNhZTkzNGYxYjcxYTM5YzkxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TAWIwA4r9tW49fTYTxwlsmoMOuIEyp6NW7dz7JKRLjo">
> 
> Looks like you can also specify `cmp.save=/path/to/folder` (https://github.com/ise-uiuc/nnsmith/blob/4061eb7347cc51880329624127113c229a7f6209/nnsmith/config/main.yaml#L65a) to save the bug report.

Thanks! Have you encountered these two types of errors when executing the model_exec command?
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/e4b87f5b-c97e-4c47-b5aa-7638f25eb437)
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/f0109bdc-d750-4c79-9df0-b863bbdd3005)
In my execution process, there were a large number of tasks such as TorchModelCPU object has no attribute 'state_dict' and Could not find an implementation for Greater (13) nodes with name '/Creator'

**Comment by ganler** [comment]
@Zeus1116 Can you retry with a fresh install of nnsmith? Thanks.

**Comment by Zeus1116** [comment]
> TorchModelCPU object has no attribute 'state_dict'

Okay, I cloned the latest project. And I rerun the command, and I found that "TorchModelCPU object has no attribute 'state_dict'" will not occur again. However, errors such as"onnxruntime.capi.onnxruntime_pybind11_state.NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for Atan(7) node with name '/Atan'
"will still occur. 
This is my script to excute the command:
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/3b7e8e5f-d25d-4df7-8695-8eaf4608b4d3)


and my nnsmith conda enviornment configuration is this:
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/ac18a1f4-8120-4f30-9200-b6d1922fd75b)
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/2f9e10ca-6adf-4af8-894f-38432356c779)
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/4085c1a3-6fd8-4bab-b233-82d03966eb14)

**Comment by Zeus1116** [comment]
> @Zeus1116 Can you retry with a fresh install of nnsmith? Thanks.

BTW, if I use the tvm as the end, it will not appear the errors. I guess the error was caused by a version update of onnxruntime.

**Comment by ganler** [comment]
So the world is not as perfect as every framework supports every model & operator in every data type :) 

Therefore, different frameworks have their own sets of support coverage -- that's what the message is saying -- we are testing the model over ONNXRuntime which does not support this particular operator & datatype.

But no worry, we considered this when building NNSmith -- You can also specify that you want to generate models with ONNXRuntime in the command:

```
- nnsmith.model_gen model.type=onnx debug.viz=true
+ nnsmith.model_gen model.type=onnx debug.viz=true backend.type=onnxruntime
```

Meanwhile, it seems that you are interested in just doing fuzzing, then you can just try:

```
nnsmith.fuzz fuzz.time={TIME} model.type=onnx backend.type=onnxruntime fuzz.root=fuzz_report
```

**Comment by Zeus1116** [comment]
> So the world is not as perfect as every framework supports every model & operator in every data type :)
> 
> Therefore, different frameworks have their own sets of support coverage -- that's what the message is saying -- we are testing the model over ONNXRuntime which does not support this particular operator & datatype.
> 
> But no worry, we considered this when building NNSmith -- You can also specify that you want to generate models with ONNXRuntime in the command:
> 
> ```
> - nnsmith.model_gen model.type=onnx debug.viz=true
> + nnsmith.model_gen model.type=onnx debug.viz=true backend.type=onnxruntime
> ```
> 
> Meanwhile, it seems that you are interested in just doing fuzzing, then you can just try:
> 
> ```
> nnsmith.fuzz fuzz.time={TIME} model.type=onnx backend.type=onnxruntime fuzz.root=fuzz_report
> ```

Thank you very much for your help! I am indeed very interested in using nnsmith for model testing, but based on my understanding of nnsmith, the fuzz command in nnsmith can only retain models that have errors in the backend compiler. My goal is to collect all the models generated by nnsmith during the fuzz process and their running results.
