### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by Zeus1116** [ise-uiuc/nnsmith#135]
### Description

I used nnsmith to generate a set of models and extracted features from them. In a model, I found a tensor with a very strange shape, as follows:
![image](https://github.com/ise-uiuc/nnsmith/assets/97088810/9f39e6e4-76ab-43ed-b6c5-dfa10982a4e3)
I don't quite understand what this li64, 40i64 is.

### Installation

pip install "git+https://github.com/ise-uiuc/nnsmith@main#egg=nnsmith[torch,onnx]" --upgrade

### Reproduction

```bash
# Paste the commands or python script for reproducing the issue.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Front-end framework

onnx

### Back-end engine

tvm

**Comment by ganler** [comment]
So first of all, it's not a bug of NNSmith but just how TVM works. By reporting bugs here you are assuming the bugs are made by NNSmith, :) therefore I removed the bug tag.

According to my TVM knowledge, the `i64` means 64bit integer so `1i64` is basically `1` whose type is `int64`.

**Comment by Zeus1116** [comment]
Thanks！
