### ISSUE TITLE
Help Wanted - How does one generate minimum code examples from NNSmith bug reports

### ISSUE THREAD

**Issue by talha-ahsan** [ise-uiuc/nnsmith#139]
Hi, apologies for this issue, I am working with NNSmith (and Neuri) and have several generated bug reports from fuzzing. However, when looking at bug reports developed as a result of NNSmith like [this one here](https://github.com/pytorch/pytorch/issues/89677) there's a minimal code sample that can be used to trigger and reproduce the bug encountered. However, I can't seem to figure out how to generate such examples utilizing NNSmith. Is there an additional utility, or a technique to do so? I can see the model.pth and pkl files, but would like a nudge or some guidance in how to utilize them to create a reproducible code sample if that makes sense? 

Sorry again for the call for help.

**Comment by syheliel** [comment]
@talha-ahsan  Hi, I think that `nnsmith.report_syn` can generate the crash code

**Comment by ganler** [comment]
Thanks for the issue. @syheliel is right we have `nnsmith.report_syn` to synthesize a bug report for PyTorch compilers. It's not perfect but should be useful in many cases (at least at the time we develop it). :D

**Comment by talha-ahsan** [comment]
Apologies for the incredibly long delay, I must've missed the notification. I'll start working with `report_syn`, thank you!

**Comment by enor2017** [comment]
Hi all, thanks for mentioning the `nnsmith.report_syn` tool, and it works well on nnsmith. However, is there any way that I can use it on `neuri` as well? I tried to adapt the `nnsmith.report_syn` codes to `neuri`, but it seems there are tons of changes required. Appreciate any inputs!
