### ISSUE TITLE
TypeError: main() got an unexpected keyword argument 'version_base'

### ISSUE THREAD

**Issue by jakc4103** [ise-uiuc/nnsmith#67]
Hi
I ran into this error, trying to run basic instruction written in Quick Start section
Any idea what might cause this error?

```
Traceback (most recent call last):
  File "/venv/test/bin/nnsmith.model_gen", line 5, in <module>
    from nnsmith.cli.model_gen import main
  File "/venv/test/lib/python3.8/site-packages/nnsmith/cli/model_gen.py", line 16, in <module>
    @hydra.main(version_base=None, config_path="../config", config_name="main")
TypeError: main() got an unexpected keyword argument 'version_base'
```

The command I used:
`nnsmith.model_gen model.type=onnx debug.viz=true`

Here is my env/lib settings/version:
```
python: 3.8.7
nnsmith: 0.0.1
z3-solver: 4.11.2
hydra-core: 1.1.2
hydra_colorlog: 1.0.0
multipledispatch: 0.6.0
appdirs: 1.4.4
```

**Comment by ganler** [comment]
@jakc4103  It turns out to be a version conflict of hydra.

Can you try:

```shell
pip install hydra-core --upgrade
pip show hydra-core # >= 1.2.0 should work
```

**Comment by ganler** [comment]
Feel free to reopen if it is not resolved. Thanks!

**Comment by jakc4103** [comment]
seems like some version conflict still exist?
```
   File "/venv/test/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/venv/test/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/venv/test/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/venv/test/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 602, in compose_config
    configure_log(cfg.hydra.hydra_logging, cfg.hydra.verbose)
  File "/venv/test/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 361, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/venv/test/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/venv/test/lib/python3.8/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/venv/test/lib/python3.8/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/venv/test/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
    return self._get_impl(
  File "/venv/test/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 453, in _get_impl
    return self._resolve_with_default(
  File "/venv/test/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: hydra.hydra_logging
    full_key: hydra.hydra_logging
    object_type=HydraConf
```

versions I used:
hydra-core: 1.2.0
omegaconf: 2.2.1

**Comment by ganler** [comment]
Hi @jakc4103 , I was able to still run it with `hydra-core==1.2.0` and `omegaconf==2.2.1` over Python3.

Can you double check with the lastest commit for using NNSmith?

```shell
pip install "git+https://github.com/ise-uiuc/nnsmith@main#egg=nnsmith[torch,onnx]" --upgrade
```

Meanwhile, please kindly find this colab script for a working example:

https://colab.research.google.com/drive/1cbLiDvDLDY_MQfH2flNYbCP9aMNlFqLX?usp=sharing

**Comment by jakc4103** [comment]
version of `hydra-colorlog` must be v1.2.0, instead of v1.0.0
otherwise one might ran into errors similar to this

> seems like some version conflict still exist?
> 
> ```
>    File "/venv/test/lib/python3.8/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
>     return func()
>   File "/venv/test/lib/python3.8/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
>     lambda: hydra.run(
>   File "/venv/test/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 105, in run
>     cfg = self.compose_config(
>   File "/venv/test/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 602, in compose_config
>     configure_log(cfg.hydra.hydra_logging, cfg.hydra.verbose)
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 361, in __getattr__
>     self._format_and_raise(key=key, value=None, cause=e)
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
>     format_and_raise(
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
>     _raise(ex, cause)
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/_utils.py", line 771, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 353, in __getattr__
>     return self._get_impl(
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 453, in _get_impl
>     return self._resolve_with_default(
>   File "/venv/test/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
>     raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
> omegaconf.errors.MissingMandatoryValue: Missing mandatory value: hydra.hydra_logging
>     full_key: hydra.hydra_logging
>     object_type=HydraConf
> ```
> 
> versions I used: hydra-core: 1.2.0 omegaconf: 2.2.1

**Comment by ganler** [comment]
Ah, I see. I'm sorry, my pypi didn't fall into this setting to tell you about this bug. 

Thanks for diagnosing this issue! Would you like to claim your contribution via a quick PR? It could be very similar to https://github.com/ise-uiuc/nnsmith/pull/68/files which just needs to add a version constraint for `hydra-colorlog` in both `requirements/core.txt` and `setup.cfg`. Of course, I can help add that if you are not interested. Thanks!
