### ISSUE TITLE
Does NNSmith support fp16?

### ISSUE THREAD

**Issue by soodoshll** [ise-uiuc/nnsmith#73]
Hi. Thanks for developing this amazing project!

Just curious if nnsmith supports generating tests with dtype float16? Directly adding float16 to `abstract/dtype.py` seems not working.

**Comment by ganler** [comment]
We had that in an experimental (private) repo. I am happy to upstream the feature you mentioned later today.

**Comment by ganler** [comment]
@soodoshll Would you like to kindly try the latest main branch which should have fp16 supported (and complex as well). Note that you will need to remove outdated cache files in `~/.cache/nnsmith-local-dev` (if you are using it locally) to re-genated latest data type configureations.

Feel free to re-open this issue if you found any further issues! 🤗
