### ISSUE TITLE
🐛 [BUG] Error: 'Key 'dtype_choices' is not in struct'

### ISSUE THREAD

**Issue by XCY-Joestar** [ise-uiuc/nnsmith#83]
### Description

I wanted to excute ```nnsmith.model_gen mgen.max_nodes=5 mgen.dtype_choices="[f32]" model.type=onnx debug.viz=false mgen.save=$path```. But it reurned :
```console
Could not override 'mgen.dtype_choices'.
To append to your config use +mgen.dtype_choices=[f32]
Key 'dtype_choices' is not in struct
    full_key: mgen.dtype_choices
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
When I excuted without ```mgen.dtype_choices="[f32]"```, it can work correctly. Could anyone tell me what should I do?

### Installation

pip install "nnsmith[torch,onnx]" --upgrade

### Reproduction

```bash
# Paste the commands or python script for reproducing the issue.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by ganler** [comment]
Hi @XCY-Joestar it seems you directly installed nnsmith via PyPI. Maybe you can temporarily install nnsmith from GitHub HEAD to use this feature:

```shell
pip install "git+https://github.com/ise-uiuc/nnsmith@main#egg=nnsmith[torch,onnx]" --upgrade
# [optional] add more front- and back-ends such as [tf] and [tvm,ort,xla,...] in "[...]"
```

My apologies for not uptating the PyPI channel timely. We will recently release the `v0.1.0` version where such features are enabled by default.

**Comment by XCY-Joestar** [comment]
@ganler Thank you for your reply. I can use nnsmtih correctly after ````pip install "git+https://github.com/ise-uiuc/nnsmith@main#egg=nnsmith[torch,onnx]" --upgrade```
