### ISSUE TITLE
💡 [REQUEST] - Consider warn for reports folder existed instead of cached

### ISSUE THREAD

**Issue by tjuwhy** [ise-uiuc/nnsmith#87]
### Motivation

Hi there, when I invoke `nnsmith.model_gen ... mgen.save=gen/`, it warns me the report folder already exists and let me choose, even if such directory doesn't exist in `$pwd`.
 

### Basic Example

If my guess is right, now it will warns me the reports folder exists if nnsmith has seen this path before.

### Drawbacks

It will facilitate the integration of nnsmith for automation, like, I was not warned to choose Y/N every single run. Is there a way to disable this reminder? :)

**Comment by ganler** [comment]
Thanks for the request. 

> it warns me the report folder already exists and let me choose, even if such directory doesn't exist in $pwd.

If you don't have `$pwd/gen` created, the warning should not prompt and it will create one for you by default. Can you provide the full command so I can help diagnose the issue?

**Comment by ganler** [comment]
Or if the `mgen.save=gen/` already exists and you just wanted to overwrite that, you can do `yes | nnsmith.model_gen ...` on Linux.

**Comment by tjuwhy** [comment]
> Or if the `mgen.save=gen/` already exists and you just wanted to overwrite that, you can do `yes | nnsmith.model_gen ...` on Linux.

Thanks, it's the solution
